server:
  port: 888
spring:
  datasource:
    url: jdbc:mysql://47.107.176.154:3306/week?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wolfsoul
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 2MB # 限制文件上传的大小
logging:
  level:
   com.dream.week.mapper: debug
jwt:
  config:
    key: dream
    ttl: 86400000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
